spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fabric_employee_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true

logging:
  level:
    org.springframework: INFO
    com.fabric.employee: DEBUG