version: '3.8'

services:
  postgres-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fabric_test
      POSTGRES_PASSWORD: fabric_test
      POSTGRES_DB: fabric_test
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    networks:
      - fabric-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fabric_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8888:8080"
    networks:
      - fabric-test-network

networks:
  fabric-test-network:
    driver: bridge

volumes:
  postgres-test-data: