version: '3.8'

services:
  auth-service:
    volumes:
      - ./services/identity/auth-service/src:/app/src
    command: mvn spring-boot:run

  user-service:
    volumes:
      - ./services/identity/user-service/src:/app/src
    command: mvn spring-boot:run