version: '3.8'

services:
  # Test containers
  postgres-test:
    image: postgres:16-alpine
    container_name: fabric-postgres-test
    environment:
      POSTGRES_USER: fabric_test
      POSTGRES_PASSWORD: fabric_test
      POSTGRES_DB: fabric_test
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    networks:
      - fabric-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fabric_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Mock services for testing
  wiremock:
    image: wiremock/wiremock:latest
    container_name: fabric-wiremock
    ports:
      - "8888:8080"
    volumes:
      - ./infrastructure/testing/wiremock:/home/wiremock
    networks:
      - fabric-test-network

  # Testing tools
  selenium-hub:
    image: selenium/hub:latest
    container_name: fabric-selenium-hub
    ports:
      - "4444:4444"
    networks:
      - fabric-test-network

  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - fabric-test-network

networks:
  fabric-test-network:
    driver: bridge

volumes:
  postgres-test-data: