package com.fabric.common.domain;

public enum Permission {
    
    // User Management
    USER_CREATE,
    USER_READ,
    USER_UPDATE,
    USER_DELETE,
    
    // Company Management
    COMPANY_CREATE,
    COMPANY_READ,
    COMPANY_UPDATE,
    COMPANY_DELETE,
    
    // Employee Management
    EMPLOYEE_CREATE,
    EMPLOYEE_READ,
    EMPLOYEE_UPDATE,
    EMPLOYEE_DELETE,
    EMPLOYEE_ASSIGN_ROLE,
    
    // Production Management - Weaving
    WEAVING_PROCESS_CREATE,
    WEAVING_PROCESS_READ,
    WEAVING_PROCESS_UPDATE,
    WEAVING_PROCESS_DELETE,
    WEAVING_MACHINE_OPERATE,
    WEAVING_MACHINE_MAINTAIN,
    
    // Production Management - Dyeing & Finishing
    DYEING_BATCH_CREATE,
    DYEING_BATCH_READ,
    DYEING_BATCH_UPDATE,
    DYEING_BATCH_DELETE,
    DYEING_RECIPE_CREATE,
    DYEING_RECIPE_READ,
    DYEING_RECIPE_UPDATE,
    DYEING_RECIPE_DELETE,
    
    FINISHING_PROCESS_CREATE,
    FINISHING_PROCESS_READ,
    FINISHING_PROCESS_UPDATE,
    FINISHING_PROCESS_DELETE,
    
    // Yarn Management
    YARN_MANAGEMENT_CREATE,
    YARN_MANAGEMENT_READ,
    YARN_MANAGEMENT_UPDATE,
    YARN_MANAGEMENT_DELETE,
    
    // Quality Control
    QUALITY_INSPECTION_CREATE,
    QUALITY_INSPECTION_READ,
    QUALITY_INSPECTION_UPDATE,
    QUALITY_INSPECTION_APPROVE,
    QUALITY_INSPECTION_REJECT,
    
    // Inventory Management
    STOCK_CREATE,
    STOCK_READ,
    STOCK_UPDATE,
    STOCK_DELETE,
    STOCK_TRANSFER,
    STOCK_AUDIT,
    
    WAREHOUSE_MANAGE,
    WAREHOUSE_RECEIVE,
    WAREHOUSE_DISPATCH,
    
    // Logistics
    SHIPPING_CREATE,
    SHIPPING_READ,
    SHIPPING_UPDATE,
    SHIPPING_TRACK,
    
    TRANSPORTATION_SCHEDULE,
    TRANSPORTATION_MANAGE,
    
    // Finance
    FINANCE_READ,
    FINANCE_CREATE,
    FINANCE_UPDATE,
    FINANCE_APPROVE,
    BUDGET_MANAGE,
    INVOICE_CREATE,
    INVOICE_APPROVE,
    PAYMENT_PROCESS,
    
    // Contact Management
    CONTACT_CREATE,
    CONTACT_READ,
    CONTACT_UPDATE,
    CONTACT_DELETE,
    
    // Notifications
    NOTIFICATION_SEND,
    NOTIFICATION_READ,
    NOTIFICATION_ADMIN,
    
    // System Administration
    SYSTEM_CONFIG,
    SYSTEM_MONITOR,
    SYSTEM_BACKUP,
    AUDIT_LOG_READ,
    
    // Reports
    REPORT_PRODUCTION,
    REPORT_INVENTORY,
    REPORT_FINANCE,
    REPORT_QUALITY,
    REPORT_EXPORT
}