apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: fabric
  labels:
    app: shipping-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8088"
    spec:
      containers:
        - name: shipping-service
          image: ${REGISTRY}/fabric-management/shipping-service:${VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: fabric-secrets
                  key: postgres-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fabric-secrets
                  key: postgres-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fabric-secrets
                  key: postgres-password
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8088
            initialDelaySeconds: 60
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8088
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: fabric-config
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: fabric
spec:
  selector:
    app: shipping-service
  ports:
    - port: 8088
      targetPort: 8088
  type: ClusterIP