spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fabric_finance_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true

logging:
  level:
    org.springframework: INFO
    com.fabric.finance: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"