# application-dev.yml
server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/fabric_auth
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    # driver-class-name: org.postgresql.Driver  # Spring Boot otomatik algılar, kaldırıldı

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # show-sql: false     # gereksiz; varsayılan zaten false
    # format_sql: true    # geliştirme anında isteğe bağlı; log kalabalığına sebep olabilir

  flyway:
    enabled: true
    # baseline-on-migrate: true  # sadece legacy veritabanı varsa gerektiğinden çoğu projede kaldırılabilir

fabric:
  security:
    jwt:
      secret: ${JWT_SECRET:VeryVerySecretKey123!ThisShouldBeStoredSecurelyInProd!}
      expiration: ${JWT_EXPIRATION:86400000}
  services:
    user-service:
      url: ${USER_SERVICE_URL:http://user-service:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.fabric: INFO
    org.springframework.security: INFO
