FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Install Maven
RUN apk add --no-cache maven

# Copy the project files (this will be mounted during development)
COPY pom.xml .
COPY fabric-parent/pom.xml fabric-parent/
COPY libraries/java/fabric-java-security/pom.xml libraries/java/fabric-java-security/
COPY infrastructure/api-gateway/pom.xml infrastructure/api-gateway/

# Resolve dependencies to enable faster compilation
RUN mvn -B dependency:go-offline -pl infrastructure/api-gateway -am

# Expose port
EXPOSE 8080

# Set the default command to run the Spring Boot app
CMD ["./mvnw", "spring-boot:run", "-f", "infrastructure/api-gateway/pom.xml", "-Dspring-boot.run.profiles=dev"]