apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-config
  namespace: fabric
data:
  application.properties: |
    spring.profiles.active=${SPRING_PROFILES_ACTIVE}
    spring.cloud.consul.host=consul
    spring.cloud.consul.port=8500
    spring.cloud.consul.discovery.prefer-ip-address=true
    spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.uuid}
    
    management.endpoints.web.exposure.include=health,info,prometheus
    management.endpoint.health.show-details=always
    management.metrics.export.prometheus.enabled=true
    
    spring.zipkin.base-url=http://zipkin:9411
    spring.sleuth.sampler.probability=1.0
    
    spring.kafka.bootstrap-servers=kafka:9092