spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  cloud:
    config:
      enabled: false

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.fabric.stock: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG