global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080', 'auth-service:8080', 'user-service:8080', 'address-service:8080', 'company-service:8080', 'contact-service:8080', 'email-service:8080', 'employee-service:8080', 'finance-service:8080', 'mail-service:8080', 'performance-service:8080', 'phone-service:8080']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']