FROM openjdk:17-jdk-slim

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
COPY src ./src

RUN chmod +x ./mvnw
RUN ./mvnw dependency:go-offline

EXPOSE 8087

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]