name: Java CI with Maven

on:
  push:
    branches: [ main, fatih ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Fix dependency issues for CI
      run: |
        # First directly install the fabric-parent POM
        chmod +x scripts/install-parent-pom.sh
        ./scripts/install-parent-pom.sh
        
        # Only fix version issues in POM files
        python3 scripts/fix-pom-versions.py
        
        # Then run CI dependency fix
        chmod +x scripts/ci-dependency-fix.sh
        ./scripts/ci-dependency-fix.sh -Dmaven.enforcer.skip=true -DskipTests
        
    - name: Verify Java commons and security libraries
      run: |
        echo "Verifying fabric-java-commons and fabric-java-security in local Maven repository"
        ls -la ~/.m2/repository/com/fabric/fabric-java-commons/ || echo "fabric-java-commons not found"
        ls -la ~/.m2/repository/com/fabric/fabric-java-security/ || echo "fabric-java-security not found"
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.enforcer.skip=true -DskipTests
      
    - name: Build logistics services
      run: |
        echo "Building logistics services specifically..."
        mvn -B package --file services/logistics/shipping-service/pom.xml -Dmaven.enforcer.skip=true -DskipTests
        mvn -B package --file services/logistics/transportation-service/pom.xml -Dmaven.enforcer.skip=true -DskipTests